install:
  - sudo pip install -r tests/deps.txt
  - mkdir -p ~/.ssh
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
  - curl -sLo - https://github.com/moul/travis-docker/raw/master/install.sh | sh -xe
  - sudo ln -s /usr/bin/docker /usr/bin/docker.io

script:
  - ./run py.test -s
  - return $(cat .exit_code)
